### ISSUE TITLE
Create simpl-games-api / PostgreSql Docker container for Simpl local dev

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#13]
This is needed for local development without installing PostgreSQl locally. Ensure the Docker container exposes port 5432 so we can "see into" the data.

This is another asset which needs to be rolled into the Dev Community side of the website & tutorials for getting started once it's available.

**Comment by janeeisenstein** [comment]
This ticket needs more explanation/requirements.

**Comment by frankwiles** [comment]
We have existing Docker containers for SIMPL API, but need to spend a few minutes to make sure there isn't anything Wharton or k8s specific about them so they are useful to others. 

We could create a simple docker-compose setup as well since the API is the one piece of SIMPL that is consistent across users. 

We should explore, ourselves, using minikube for local development (or at least compose) for other reasons unrelated to why we should have this for open source users.

**Comment by janeeisenstein** [comment]
Completed as part of the Django 2.2 upgrade.
