### ISSUE TITLE
Investigate vulnerability in dependency

### ISSUE THREAD

**Issue by joelee484** [simplworld/simpl.world.website#65]
Github has detected a vulnerability in one of our website dependencies.  @jefftriplett or @frankwiles can you take a look when you have a chance and resolve?  Thanks!  https://github.com/simplworld/simpl.world.website/network/dependencies

**Comment by jefftriplett** [comment]
@joelee484 this is basically a red herring, but it's easy to fix. Since your website is served statically, there isn't an attack vector with that library. GitHub compiles everything and then they handle the serving of pages. 

That said, I'll update everything to the latest version of Jekyll which will make that warning go away.

**Comment by jefftriplett** [comment]
Upgraded in my PR and all show as 👍  now - https://github.com/simplworld/simpl.world.website/network/dependencies
